### ISSUE TITLE
PA Review: Bookmark events

### ISSUE THREAD

**Issue by cyl47** [cylinda47/eventize#1]

**Comment by LochandQuay** [comment]
@cylinda47 

Looks like it's only partially done. No bookmarking functionality on the event pages, only the index.

**Comment by cyl47** [comment]
@LochandQuay fixed

**Comment by LochandQuay** [comment]
@cylinda47 

The dashboard of saved/upcoming/owned events doesn't work. If you don't get this working in time, I would just remove the link to this page.
