### ISSUE TITLE
PA Review: Categories

### ISSUE THREAD

**Issue by cyl47** [cylinda47/eventize#2]

**Comment by cyl47** [comment]
@LochandQuay 

Categories features is in Browse Events and all the tags in event details. Organizer is allowed to tag / untag the category for their event.

**Comment by LochandQuay** [comment]
@cylinda47 

Little details:
- [ ] You lost the font styling on your event index items when you go by a category, and the entire index item no longer appears to work as a link (the image doesn't).
- [ ] The hashtagged links to the category page doesn't work. It flickers for a second then redirects back to the index.
