### ISSUE TITLE
PA Review: Events

### ISSUE THREAD

**Issue by cyl47** [cylinda47/eventize#4]

**Comment by LochandQuay** [comment]
@cylinda47 

Me: *sees create event link when not logged in, clicks it*
*Login modal pops up*
Me: 😮  😍 

Console Errors:
- [x] `Uncaught TypeError: Cannot read property 'style' of undefined` (twice in a row)

Functionality Issues:
- [ ] Might be an issue with the time settings on your computer or perhaps how JavaScript accepts the time...but I set my event to be Wednesday from 7:30pm to 8:30pm and it shows on the event page as Tuesday from 11:30pm to 12:30pm PST.
- [ ] Try scrolling as far as you can down on the event index page and then clicking an event. Chances are the page rendered scrolled down still. This is a common issue with SPAs...you can easily fix it with a lifecycle method and `window.scrollTo(0, 0)`.

Styling Issues:
- [x] Can't view the submit button unless you're hovering over it. Seems odd.

BUT WOW THIS IS AMAZING! The image displayed like immediately after I added it to the event and Rich Text Editing on the event form is so above and beyond what was needed! I'm seriously impressed. Good work!

**Comment by LochandQuay** [comment]
- [x] Clear errors when on edit form and clicking on Create Event (I had a fresh event form and errors)

**Comment by cyl47** [comment]
@LochandQuay fixed

**Comment by LochandQuay** [comment]
@cylinda47 

Please don't forget to fix these!
- [ ] Might be an issue with the time settings on your computer or perhaps how JavaScript accepts the time...but I set my event to be Wednesday from 7:30pm to 8:30pm and it shows on the event page as Tuesday from 11:30pm to 12:30pm PST.
- [ ] Try scrolling as far as you can down on the event index page and then clicking an event. Chances are the page rendered scrolled down still. This is a common issue with SPAs...you can easily fix it with a lifecycle method and window.scrollTo(0, 0).
