### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by cyl47** [cylinda47/eventize#7]

**Comment by LochandQuay** [comment]
@cylinda47 

Functionality Issues:
- [x] Would prefer to be able to toggle between forms. Currently you can get to the sign up form from the sign in form but you can get back.

Styling Issues:
- [x] _Sometimes_ the little 'x' in the top right corner doesn't show. Not sure what's going on there. It'll only happened to me twice when I first opened the page. 
- [ ] You're inconsistent with how errors are displayed between the forms. Also, the errors on the Sign Up form are VERY small. Not a big deal, but something worth pointing out.

General Issues (will need to be addressed sometime before the due date):
- [ ] `Mixed Content Warning` [Console Error]: This is a pretty easy one to fix. Your site should be running on HTTPS, but your images are linked as HTTP. If you change them to be HTTPS, the warning should go away. :)
- [ ] `Minification Warning` [Console Error]: There's a reading in the FSP docs on how to get rid of this.

**Comment by LochandQuay** [comment]
@cylinda47 

Saw your updates. Love the changes you've made.
A couple things that has now popped up:
- [ ] Hitting enter on the session forms doesn't appear to trigger the `onSubmit`. Do you have the button as an `onClick`? 
- [x] If you're on an event page and you get a Sign In form error, it doesn't appear on the form, but somewhere on the event page. The Sign Up form is fine, though.
